version: "3.1"
services:
  app:
    image: timbuild 
    container_name: timbuild_bot
    build: 
      context: .
      dockerfile: .
    restart: "no"
    ports:
     
      - 8000:8000
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - timbuild

    command: "php artisan serve --host=0.0.0.0 --port=8000"

   

  db:
    image: mysql:latest
    container_name: mysql_db_timbuild
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data_timbuild:/docker-entrypoint-initdb.d
      - db_data_timbuild:/var/lib/mysql
    networks:
      - timbuild
   
  
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    restart: "no"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - timbuild


networks:
  timbuild:
    driver: bridge


volumes:
  db_data_timbuild: